---
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/code/java/homeloans/config/repo/
#          uri: https://github.com/conor10/homeloans/config/repo

server:
  port: 8888
