---
spring:
  cloud:
    config:
      server:
        git:
          # we have to point to the repo base directory
          uri: file://${user.home}/code/java/homeloans/
#          uri: https://github.com/conor10/homeloans/
          searchPaths: config-repo

server:
  port: 8888
