---
eureka:
  instance:
    hostname: localhost
  # Uncomment to run in stand-alone mode - i.e. don't search for peers
#  client:
#    registerWithEureka: false
#    fetchRegistry: false

server:
  port: 8761

---
spring:
  profiles: dev
